<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.bibletechnologies.net/2003/OSIS/namespace"
    xmlns:osis="http://www.bibletechnologies.net/2003/OSIS/namespace"
    elementFormDefault="qualified"
    attributeFormDefault="unqualified"
    version="2.1.1-project-subset">
  <xs:element name="osis">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="osisText" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:any minOccurs="2" maxOccurs="unbounded" processContents="lax"/>
            </xs:sequence>
            <xs:attribute name="osisIDWork" type="xs:string" use="required"/>
            <xs:attribute name="osisRefWork" type="xs:string" use="required"/>
            <xs:anyAttribute processContents="lax"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:anyAttribute processContents="lax"/>
    </xs:complexType>
  </xs:element>
</xs:schema>
