#include "core/lexicon.h"

#include "core/data_paths.h"
#include "core/hebrew_forms.h"
#include "core/tokenize.h"

#include <QFile>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonValue>
#include <QRegularExpression>

namespace milah {
namespace {

const QRegularExpression &cantillation()
{
    static const QRegularExpression expression(QStringLiteral("[\\x{0591}-\\x{05AF}]"));
    return expression;
}

const QRegularExpression &punctuation()
{
    static const QRegularExpression expression(
        QStringLiteral("[\\p{P}\\p{S}]"),
        QRegularExpression::UseUnicodePropertiesOption);
    return expression;
}

QHash<QString, QString> readIndex(const QJsonObject &source)
{
    QHash<QString, QString> index;
    index.reserve(source.size());
    for (auto item = source.constBegin(); item != source.constEnd(); ++item) {
        QStringList numbers;
        const QJsonArray candidates = item.value().toArray();
        numbers.reserve(candidates.size());
        for (const QJsonValue &candidate : candidates) {
            numbers.append(candidate.toString());
        }
        index.insert(item.key(), numbers.join(QLatin1Char(' ')));
    }
    return index;
}

/// Whether a form and the entry it is filed under could be the same word, at
/// the weakest strength that says anything at all: they share a consonant.
///
/// Deliberately this weak. Hebrew loses radicals freely — נָתַן is written תֵּן,
/// הָלַךְ is written לֵךְ — so anything stricter starts refusing real
/// inflections. What it does catch is a pairing that cannot be a spelling of
/// the same word under any morphology, which is what a join built by counting
/// co-occurrences in a corpus will occasionally produce.
bool couldBeTheSameWord(const QString &form, const QString &lemma)
{
    const QString written = foldedKey(form);
    const QString root = foldedKey(lemma);
    if (written.isEmpty() || root.isEmpty()) {
        // Nothing to judge on, so nothing to object to.
        return true;
    }
    for (const QChar letter : written) {
        if (root.contains(letter)) {
            return true;
        }
    }
    return false;
}

/// Drops the candidates an index names that its own entries contradict.
///
/// The shipped index is generated by counting which Strong's numbers each
/// inflected form appears with in the Westminster Leningrad Codex, and a form
/// can pick up the number of the word beside it. Two rows of the current file
/// do: `בו` "in him" is filed under H8055 שָׂמַח "to rejoice", and `לי` "to me"
/// under H7121 קָרָא "to call" — both prepositions carrying a pronominal
/// suffix, which Strong's has no entry for at all, wearing the number of the
/// verb they follow.
///
/// Done once here rather than inside numbersFor(): the test needs the entry's
/// lemma, and the alignment asks strongsFor() for every token of every witness.
/// One pass beside a multi-megabyte parse costs nothing; a pass per lookup
/// would be felt.
void pruneIndex(
    QHash<QString, QString> &index,
    const QHash<QString, LexiconEntry> &entries)
{
    for (auto item = index.begin(); item != index.end();) {
        const QStringList numbers =
            item.value().split(QLatin1Char(' '), Qt::SkipEmptyParts);
        QStringList kept;
        kept.reserve(numbers.size());
        for (const QString &number : numbers) {
            const auto entry = entries.constFind(number);
            // A number with no entry shipped says nothing about itself, so
            // there is nothing for it to disagree with. It still reaches the
            // marker as a bare number, which is what it always did.
            if (entry == entries.constEnd()
                || couldBeTheSameWord(item.key(), entry->lemma)) {
                kept.append(number);
            }
        }
        if (kept.isEmpty()) {
            item = index.erase(item);
        } else {
            item.value() = kept.join(QLatin1Char(' '));
            ++item;
        }
    }
}

HebrewLexicon parse(const QByteArray &json)
{
    HebrewLexicon lexicon;
    QJsonParseError error;
    const QJsonDocument document = QJsonDocument::fromJson(json, &error);
    if (error.error != QJsonParseError::NoError || !document.isObject()) {
        return lexicon;
    }
    return HebrewLexicon::fromJson(document.object());
}

} // namespace

HebrewLexicon HebrewLexicon::fromJson(const QJsonObject &document)
{
    HebrewLexicon lexicon;
    lexicon.m_pointed = readIndex(document.value(QStringLiteral("pointed")).toObject());
    lexicon.m_forms = readIndex(document.value(QStringLiteral("forms")).toObject());

    const QJsonObject entries = document.value(QStringLiteral("entries")).toObject();
    lexicon.m_entries.reserve(entries.size());
    for (auto item = entries.constBegin(); item != entries.constEnd(); ++item) {
        const QJsonObject record = item.value().toObject();
        lexicon.m_entries.insert(
            item.key(),
            LexiconEntry{
                item.key(),
                record.value(QStringLiteral("l")).toString(),
                record.value(QStringLiteral("x")).toString(),
                record.value(QStringLiteral("p")).toString(),
                record.value(QStringLiteral("d")).toString(),
                record.value(QStringLiteral("g")).toString(),
                record.value(QStringLiteral("k")).toString(),
                record.value(QStringLiteral("bg")).toString(),
                record.value(QStringLiteral("bd")).toString(),
                record.value(QStringLiteral("m")).toString(),
            });
    }

    // Last, because it is the entries that judge the indexes.
    pruneIndex(lexicon.m_forms, lexicon.m_entries);
    pruneIndex(lexicon.m_pointed, lexicon.m_entries);
    return lexicon;
}

QString pointedKey(const QString &text)
{
    QString result = text.normalized(QString::NormalizationForm_D);
    result.remove(cantillation());
    result.remove(punctuation());
    return result.normalized(QString::NormalizationForm_C).trimmed();
}

QString strongsTooltip(const QList<LexiconEntry> &entries)
{
    if (entries.isEmpty()) {
        return QString();
    }

    QStringList blocks;
    for (const LexiconEntry &entry : entries) {
        QStringList lines;

        // Headline: the number, how the word is written and said, and what
        // part of speech it is.
        QStringList headline{entry.strongs};
        if (!entry.lemma.isEmpty()) {
            headline.append(entry.lemma);
        }
        if (!entry.transliteration.isEmpty()) {
            headline.append(QStringLiteral("(%1)").arg(entry.transliteration));
        }
        if (!entry.morphology.isEmpty()) {
            headline.append(QStringLiteral("[%1]").arg(entry.morphology));
        }
        lines.append(headline.join(QLatin1Char(' ')));

        if (!entry.briefGloss.isEmpty()) {
            lines.append(entry.briefGloss);
        }
        if (!entry.meaning.isEmpty()) {
            lines.append(QString());
            lines.append(entry.meaning);
        }

        // Strong's own wording last: it is the older and more slanted of the
        // two, and worth having but not worth leading with.
        if (!entry.gloss.isEmpty() && entry.gloss != entry.briefGloss) {
            lines.append(QString());
            lines.append(QStringLiteral("Strong's: %1").arg(entry.gloss));
        }
        if (!entry.derivation.isEmpty()) {
            lines.append(QStringLiteral("From: %1").arg(entry.derivation));
        }
        if (!entry.kjvUsage.isEmpty()) {
            lines.append(QStringLiteral("KJV: %1").arg(entry.kjvUsage));
        }

        blocks.append(lines.join(QLatin1Char('\n')));
    }

    if (blocks.size() > 1) {
        blocks.prepend(
            QStringLiteral("%1 possible readings:").arg(blocks.size()));
    }
    return blocks.join(QStringLiteral("\n\n"));
}

const HebrewLexicon &HebrewLexicon::shared()
{
    static const HebrewLexicon lexicon = [] {
        const QString path = locateDataFile(QStringLiteral("hebrew_lexicon.json"));
        HebrewLexicon loaded = path.isEmpty() ? HebrewLexicon() : fromFile(path);
        // A separate file, and an optional one: a data directory without it
        // simply has no opinion about roots. Kept out of the dictionary itself
        // because that is six megabytes on one line, and the roots are derived
        // from it rather than shipped with it.
        loaded.loadRoots(locateDataFile(QStringLiteral("hebrew_roots.json")));
        return loaded;
    }();
    return lexicon;
}

HebrewLexicon HebrewLexicon::fromFile(const QString &path)
{
    QFile file(path);
    if (!file.open(QIODevice::ReadOnly)) {
        return HebrewLexicon();
    }
    return parse(file.readAll());
}

QStringList HebrewLexicon::strongsFor(const QString &word) const
{
    return numbersFor(word).split(QLatin1Char(' '), Qt::SkipEmptyParts);
}

void HebrewLexicon::loadRoots(const QString &path)
{
    if (path.isEmpty()) {
        return;
    }
    QFile file(path);
    if (!file.open(QIODevice::ReadOnly)) {
        return;
    }
    const QJsonDocument document = QJsonDocument::fromJson(file.readAll());
    if (!document.isObject()) {
        return;
    }

    const QJsonObject roots =
        document.object().value(QStringLiteral("roots")).toObject();
    m_roots.reserve(roots.size());
    for (auto item = roots.constBegin(); item != roots.constEnd(); ++item) {
        const QString root = item.value().toString();
        // A word that is its own root tells the scorer nothing it does not
        // already get from the Strong's number itself.
        if (!root.isEmpty() && root != item.key()) {
            m_roots.insert(item.key(), root);
        }
    }
}

QStringList HebrewLexicon::rootsFor(const QString &word) const
{
    if (m_roots.isEmpty()) {
        return QStringList();
    }

    QStringList roots;
    for (const QString &number : strongsFor(word)) {
        const auto root = m_roots.constFind(number);
        if (root != m_roots.constEnd() && !roots.contains(root.value())) {
            roots.append(root.value());
        }
    }
    return roots;
}

QString HebrewLexicon::numbersFor(const QString &word) const
{
    // Pointed first: it distinguishes readings the consonants alone cannot.
    const QString pointed = pointedKey(word);
    if (!pointed.isEmpty()) {
        const auto match = m_pointed.constFind(pointed);
        if (match != m_pointed.constEnd()) {
            return match.value();
        }
    }

    const QString consonantal = comparisonKey(word);
    if (consonantal.isEmpty()) {
        return QString();
    }
    const auto match = m_forms.constFind(consonantal);
    if (match != m_forms.constEnd()) {
        return match.value();
    }

    // Hebrew prefixes agglutinate and the index holds the forms the Masoretic
    // text happens to use, so a word carrying an extra prefix misses. Peeling
    // one or two prefix letters recovers most of those. The stripped form is
    // only accepted when it is itself in the index, which keeps the heuristic
    // from inventing readings out of coincidental letter sequences.
    for (int peeled = 1; peeled <= 2 && peeled + 1 < consonantal.size(); ++peeled) {
        if (!isPrefixLetter(consonantal.at(peeled - 1))) {
            break;
        }
        const auto stripped = m_forms.constFind(consonantal.mid(peeled));
        if (stripped != m_forms.constEnd()) {
            return stripped.value();
        }
    }

    return QString();
}

QList<LexiconEntry> HebrewLexicon::lookup(const QString &word) const
{
    QList<LexiconEntry> result;
    const QString numbers = numbersFor(word);
    if (numbers.isEmpty()) {
        return result;
    }

    for (const QString &number : numbers.split(QLatin1Char(' '), Qt::SkipEmptyParts)) {
        const auto entry = m_entries.constFind(number);
        if (entry != m_entries.constEnd()) {
            result.append(entry.value());
        } else {
            result.append(LexiconEntry{number, QString(), QString(), QString()});
        }
    }
    return result;
}

bool HebrewLexicon::knows(const QString &word) const
{
    return !numbersFor(word).isEmpty();
}

} // namespace milah
